/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pb_19130911_proyecto_03;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author laplant
 */
public class PB_19130911_JFrameInicio_3 extends javax.swing.JFrame {

    /**
     * Creates new form PB_19130911_JFrameInicio_3
     */
    Graphics g;
    Instrumento instrumento;
    
    Laud laud;
    Shamisen shamisen;
    Campana campana;
    Cajon cajon;
    ArregloInstrumentos arreglo;
    
    public PB_19130911_JFrameInicio_3() {
        super("Inicial");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLaud = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableShamisen = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableCampana = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableCajon = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonEjemplo = new javax.swing.JButton();
        jButtonMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableLaud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Marca", ""},
                {"Precio", null},
                {"Tipo", null}
            },
            new String [] {
                "Atributos", "Laúd"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableLaud);
        if (jTableLaud.getColumnModel().getColumnCount() > 0) {
            jTableLaud.getColumnModel().getColumn(0).setPreferredWidth(60);
        }

        jTableShamisen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Marca", ""},
                {"Precio", null},
                {"Piel", null}
            },
            new String [] {
                "Atributos", "Shamisen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableShamisen);
        if (jTableShamisen.getColumnModel().getColumnCount() > 0) {
            jTableShamisen.getColumnModel().getColumn(0).setPreferredWidth(60);
        }

        jTableCampana.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Marca", ""},
                {"Precio", null},
                {"Material", null}
            },
            new String [] {
                "Atributos", "Campana"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableCampana);
        if (jTableCampana.getColumnModel().getColumnCount() > 0) {
            jTableCampana.getColumnModel().getColumn(0).setPreferredWidth(60);
        }

        jTableCajon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Marca", ""},
                {"Precio", null},
                {"Madera", null}
            },
            new String [] {
                "Atributos", "Cajón"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableCajon);
        if (jTableCajon.getColumnModel().getColumnCount() > 0) {
            jTableCajon.getColumnModel().getColumn(0).setPreferredWidth(60);
        }

        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Cuerdas");

        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("Percusión");

        jButtonEjemplo.setText("Ejemplo");
        jButtonEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjemploActionPerformed(evt);
            }
        });

        jButtonMostrar.setText("Mostrar y ordenar");
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonMostrar)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel2)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonEjemplo)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEjemplo)
                    .addComponent(jButtonMostrar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjemploActionPerformed
        laud = new Laud();
        shamisen = new Shamisen();
        campana = new Campana();
        cajon = new Cajon();
        
        /*Si, aquí me di cuenta de que pude haber simplificado esto poniendo un
          atributo global en la clase padre Instrumento para poder hacer un método para
          mostrar en la tabla y que todas las subclases la implementen de distintas formas*/
        
        jTableLaud.setValueAt(laud.getMarca(), 0, 1);
        jTableLaud.setValueAt(laud.getPrecio(), 1, 1);
        jTableLaud.setValueAt(laud.getTipo(), 2, 1);
        
        jTableShamisen.setValueAt(shamisen.getMarca(), 0, 1);
        jTableShamisen.setValueAt(shamisen.getPrecio(), 1, 1);
        jTableShamisen.setValueAt(shamisen.getPiel(), 2, 1);
        
        jTableCampana.setValueAt(campana.getMarca(), 0, 1);
        jTableCampana.setValueAt(campana.getPrecio(), 1, 1);
        jTableCampana.setValueAt(campana.getMaterial(), 2, 1);
        
        jTableCajon.setValueAt(cajon.getMarca(), 0, 1);
        jTableCajon.setValueAt(cajon.getPrecio(), 1, 1);
        jTableCajon.setValueAt(cajon.getMadera(), 2, 1);
    }//GEN-LAST:event_jButtonEjemploActionPerformed

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
        laud = new Laud(jTableLaud.getValueAt(0, 1)+"", 
                (double)jTableLaud.getValueAt(1, 1),
                        jTableLaud.getValueAt(2, 1)+"");
        
        shamisen = new Shamisen(jTableShamisen.getValueAt(0, 1)+"", 
                        (double)jTableShamisen.getValueAt(1, 1),
                                jTableShamisen.getValueAt(2, 1)+"");
        
        campana = new Campana(jTableCampana.getValueAt(0, 1)+"", 
                      (double)jTableCampana.getValueAt(1, 1),
                              jTableCampana.getValueAt(2, 1)+"");
        
        cajon = new Cajon(jTableCajon.getValueAt(0, 1)+"", 
                  (double)jTableCajon.getValueAt(1, 1),
                          jTableCajon.getValueAt(2, 1)+"");
        
        arreglo = new ArregloInstrumentos(laud,shamisen,campana,cajon);
        
        PB_19130911_JFramePrincipal_3 principal = new PB_19130911_JFramePrincipal_3(this);
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonMostrarActionPerformed

    public ArregloInstrumentos getArreglo()
    {
        return arreglo;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PB_19130911_JFrameInicio_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PB_19130911_JFrameInicio_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PB_19130911_JFrameInicio_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PB_19130911_JFrameInicio_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PB_19130911_JFrameInicio_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEjemplo;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableCajon;
    private javax.swing.JTable jTableCampana;
    private javax.swing.JTable jTableLaud;
    private javax.swing.JTable jTableShamisen;
    // End of variables declaration//GEN-END:variables
}
